source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Client' do
  pod 'SwiftProtobuf', :git => 'git@github.com:apple/swift-protobuf.git', :tag => '0.9.26'
  pod 'APIKit'
end
