/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: talk.proto
 *
 */

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _1: SwiftProtobuf.ProtobufAPIVersion_1 {}
  typealias Version = _1
}

struct Talk: SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "Talk"
  static let protoPackageName: String = ""
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "title"),
    3: .same(proto: "desc"),
    4: .same(proto: "speaker"),
    5: .same(proto: "tags"),
  ]

  private class _StorageClass {
    var _id: Int32 = 0
    var _title: String = ""
    var _desc: String = ""
    var _speaker: User? = nil
    var _tags: [String] = []

    init() {}

    func copy() -> _StorageClass {
      let clone = _StorageClass()
      clone._id = _id
      clone._title = _title
      clone._desc = _desc
      clone._speaker = _speaker
      clone._tags = _tags
      return clone
    }
  }

  private var _storage = _StorageClass()

  private mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _storage.copy()
    }
    return _storage
  }

  var id: Int32 {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  var title: String {
    get {return _storage._title}
    set {_uniqueStorage()._title = newValue}
  }

  var desc: String {
    get {return _storage._desc}
    set {_uniqueStorage()._desc = newValue}
  }

  var speaker: User {
    get {return _storage._speaker ?? User()}
    set {_uniqueStorage()._speaker = newValue}
  }
  var hasSpeaker: Bool {
    return _storage._speaker != nil
  }
  mutating func clearSpeaker() {
    return _storage._speaker = nil
  }

  var tags: [String] {
    get {return _storage._tags}
    set {_uniqueStorage()._tags = newValue}
  }

  init() {}

  mutating func _protobuf_generated_decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        try decodeField(decoder: &decoder, fieldNumber: fieldNumber)
      }
    }
  }

  mutating func _protobuf_generated_decodeField<D: SwiftProtobuf.Decoder>(decoder: inout D, fieldNumber: Int) throws {
    switch fieldNumber {
    case 1: try decoder.decodeSingularInt32Field(value: &_storage._id)
    case 2: try decoder.decodeSingularStringField(value: &_storage._title)
    case 3: try decoder.decodeSingularStringField(value: &_storage._desc)
    case 4: try decoder.decodeSingularMessageField(value: &_storage._speaker)
    case 5: try decoder.decodeRepeatedStringField(value: &_storage._tags)
    default: break
    }
  }

  func _protobuf_generated_traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._id != 0 {
        try visitor.visitSingularInt32Field(value: _storage._id, fieldNumber: 1)
      }
      if !_storage._title.isEmpty {
        try visitor.visitSingularStringField(value: _storage._title, fieldNumber: 2)
      }
      if !_storage._desc.isEmpty {
        try visitor.visitSingularStringField(value: _storage._desc, fieldNumber: 3)
      }
      if let v = _storage._speaker {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }
      if !_storage._tags.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._tags, fieldNumber: 5)
      }
    }
  }

  func _protobuf_generated_isEqualTo(other: Talk) -> Bool {
    return withExtendedLifetime((_storage, other._storage)) { (_storage, other_storage) in
      if _storage !== other_storage {
        if _storage._id != other_storage._id {return false}
        if _storage._title != other_storage._title {return false}
        if _storage._desc != other_storage._desc {return false}
        if _storage._speaker != other_storage._speaker {return false}
        if _storage._tags != other_storage._tags {return false}
      }
      return true
    }
  }
}

struct TalkResponse: SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "TalkResponse"
  static let protoPackageName: String = ""
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "talks"),
  ]

  var talks: [Talk] = []

  init() {}

  mutating func _protobuf_generated_decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      try decodeField(decoder: &decoder, fieldNumber: fieldNumber)
    }
  }

  mutating func _protobuf_generated_decodeField<D: SwiftProtobuf.Decoder>(decoder: inout D, fieldNumber: Int) throws {
    switch fieldNumber {
    case 1: try decoder.decodeRepeatedMessageField(value: &talks)
    default: break
    }
  }

  func _protobuf_generated_traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !talks.isEmpty {
      try visitor.visitRepeatedMessageField(value: talks, fieldNumber: 1)
    }
  }

  func _protobuf_generated_isEqualTo(other: TalkResponse) -> Bool {
    if talks != other.talks {return false}
    return true
  }
}

struct LikeRequest: SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "LikeRequest"
  static let protoPackageName: String = ""
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
  ]

  var id: Int32 = 0

  init() {}

  mutating func _protobuf_generated_decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      try decodeField(decoder: &decoder, fieldNumber: fieldNumber)
    }
  }

  mutating func _protobuf_generated_decodeField<D: SwiftProtobuf.Decoder>(decoder: inout D, fieldNumber: Int) throws {
    switch fieldNumber {
    case 1: try decoder.decodeSingularInt32Field(value: &id)
    default: break
    }
  }

  func _protobuf_generated_traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if id != 0 {
      try visitor.visitSingularInt32Field(value: id, fieldNumber: 1)
    }
  }

  func _protobuf_generated_isEqualTo(other: LikeRequest) -> Bool {
    if id != other.id {return false}
    return true
  }
}

struct LikeResponse: SwiftProtobuf.Proto3Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "LikeResponse"
  static let protoPackageName: String = ""
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "result"),
  ]

  var result: Bool = false

  init() {}

  mutating func _protobuf_generated_decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      try decodeField(decoder: &decoder, fieldNumber: fieldNumber)
    }
  }

  mutating func _protobuf_generated_decodeField<D: SwiftProtobuf.Decoder>(decoder: inout D, fieldNumber: Int) throws {
    switch fieldNumber {
    case 1: try decoder.decodeSingularBoolField(value: &result)
    default: break
    }
  }

  func _protobuf_generated_traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if result != false {
      try visitor.visitSingularBoolField(value: result, fieldNumber: 1)
    }
  }

  func _protobuf_generated_isEqualTo(other: LikeResponse) -> Bool {
    if result != other.result {return false}
    return true
  }
}
